name: mynewspod
description: news list with favs

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  webfeed: ^0.4.2
  provider: ^3.1.0+1
  http: ^0.12.0+2
  path_provider: ^1.4.0
  path: ^1.6.4
  moor_flutter: ^2.0.0
  url_launcher: ^5.4.1
  pedantic: ^1.8.0+1

dev_dependencies:
  moor_generator: ^2.0.0
  build_runner: ^1.7.2

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
